plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/opt/data/projects/burger-lab/v2"
publishOrigin = "default"
base = "/opt/data/projects/burger-lab/v2"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]